baseURL = "https://www.kenardapara.com"
languageCode = "en"
title = "Kenarda Para"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
#disqusShortname = "disqus_shortname"

# Google Analytics UA number
googleAnalytics = "UA-119026185-1"
disqusShortname = "kenardapara"

# Copyright of your post
#copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Blog"
  weight = 10
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Etiketler"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "VaryemezAmca"
  avatar = "/img/favicon-1024.png"
  seotitle = "Kenarda Para, Pasif Yatırım, Finansal Özgürlük ve Bireysel Emeklilik Üzerine Bir Blog"
  subtitle = "İlerde lazım olur"
  description = "Kenarda parasıyla finansal özgürlük kazanmak isteyenlere yazılar ve veriye dayalı analizler"
  paginate = 10

  # Choose your social networks
  email = "info@kenardapara.com"
  github = "KenardaPara"
  twitter = "kenardapara"
  # linkedin = "linkedin_username"
  # weibo = "weibo_username"
  # wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"

  # Google Webmaster
  # https://www.google.com/webmasters/>
#  googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
#  msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"
